# Generated by Django 4.0.6 on 2024-12-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='foto_platillo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_platillo/'),
        ),
    ]
