# Generated by Django 4.0.6 on 2024-12-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comida', '0002_platillo_foto_platillo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
