# Generated by Django 4.0.6 on 2024-12-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comida', '0004_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
