# Generated by Django 4.0.6 on 2024-12-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comida', '0005_alter_platillo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='tipo',
            field=models.CharField(choices=[('sopa', 'Sopa'), ('segundo', 'Segundo'), ('jugo', 'Jugo'), ('postre', 'Postre'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
