# Generated by Django 4.0.6 on 2024-12-26 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Comida', '0007_alter_platillo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='fecha_disponible',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
