# Generated by Django 4.0.6 on 2024-12-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comida', '0008_alter_platillo_fecha_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
