# Generated by Django 4.0.6 on 2024-12-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comida', '0009_platillo_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='tipo',
            field=models.CharField(choices=[('Sopa', 'Sopa'), ('Segundo', 'Segundo'), ('Bebida', 'Bebida'), ('Postre', 'Postre'), ('Otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
